Snakemake check if locally build successful, else pull from registry; New container tag 0.2 instead of latest; Update bowtie container tag in Contextmap

diff --git a/scripts/snakemake/Snakefile b/scripts/snakemake/Snakefile
--- a/scripts/snakemake/Snakefile
+++ b/scripts/snakemake/Snakefile
@@ -21,6 +21,7 @@ except KeyError:
 
 working_directory = os.getcwd()
 docker_prefix = "gitlab.lrz.de:5005/ge46ban/dockers/develop/"
+container_version = "0.2"
 
 rule all:
     input:
@@ -51,7 +52,13 @@ rule get_base_os_docker:
     shell:
         """
         mkdir -p output/snakemake/
-        docker pull gitlab.lrz.de:5005/ge46ban/dockers/develop/base-image | tee {output}
+
+        if docker-compose -f scripts/snakemake/docker-compose.yml build base ; then
+            echo "Build base image locally" | tee {output}
+        else 
+            echo "\nLocal build failed, pulling image from registry" | tee {output}
+            docker pull {docker_prefix}base-image | tee {output}
+        fi
         """
 
 rule run_asimulator_rule:
@@ -91,18 +98,31 @@ rule run_mapping_tools_rule:
             for tool in {params.tools}
             do
                 echo "Started $tool at $(date)" | tee {output}
-                docker pull gitlab.lrz.de:5005/ge46ban/dockers/develop/$tool
-                docker run -v {working_directory}:/MOUNT --user $(id -u):$(id -g) --rm {docker_prefix}$tool
-		casedir=output/"$tool"-output/casedir
-		if [ -d "$casedir" ]; then
-                        find "$casedir" \( -name "*.sam" -o -name "*.bam" \) -exec cp {{}} input/casedir/bamdir/ \;
+                
+                if docker-compose -f scripts/snakemake/docker-compose.yml build $tool ; then
+                    echo "Build $tool locally" | tee {output}
+                    container_prefix="dicast/"
+                else 
+                    echo "\nLocal build failed, pulling image from registry..." | tee {output}
+                    docker pull {docker_prefix}$tool:{container_version}
+                    echo "Done" | tee {output}
+                    container_prefix={docker_prefix}
+                fi
+
+                docker run -v {working_directory}:/MOUNT --user $(id -u):$(id -g) --rm $container_prefix"$tool":{container_version}
+
+                casedir=output/"$tool"-output/casedir
+                if [ -d "$casedir" ]; then
+                    find "$casedir" -exec chmod 777 {{}} \;
+                    find "$casedir" \( -name "*.sam" -o -name "*.bam" \) -exec cp {{}} input/casedir/bamdir/ \;
                 else
                         echo "No case directory found, assuming non-differential run"
                 fi
-		find output/"$tool"-output/controldir/ -exec chmod 777 {{}} \;
-		find output/"$tool"-output/controldir/ \( -name "*.sam" -o -name "*.bam" \) -exec cp -p {{}} input/controldir/bamdir/ \;
-		echo "Finished $tool at $(date)" | tee {output}
-		echo -e "\n\n"
+
+                find output/"$tool"-output/controldir/ -exec chmod 777 {{}} \;
+                find output/"$tool"-output/controldir/ \( -name "*.sam" -o -name "*.bam" \) -exec cp -p {{}} input/controldir/bamdir/ \;
+                echo "Finished $tool at $(date)" | tee {output}
+                echo -e "\n\n"
             done
         fi
         """
@@ -124,8 +144,18 @@ rule run_as_detection_tools:
             for tool in {params.tools}
             do
                 echo "Started $tool at $(date)" | tee {output}
-                docker pull gitlab.lrz.de:5005/ge46ban/dockers/develop/$tool
-                docker run -v {working_directory}:/MOUNT --user $(id -u):$(id -g) --rm {docker_prefix}$tool
+                
+                if docker-compose -f scripts/snakemake/docker-compose.yml build $tool ; then
+                    echo "Build $tool locally" | tee {output}
+                    container_prefix="dicast/"
+                else 
+                    echo "\nLocal build failed, pulling image from registry" | tee {output}
+                    docker pull {docker_prefix}$tool:{container_version}
+                    echo "Done" | tee {output}
+                    container_prefix={docker_prefix}
+                fi
+                
+                docker run -v {working_directory}:/MOUNT --user $(id -u):$(id -g) --rm $container_prefix"$tool":{container_version}
                 echo "Finished $tool at $(date)" | tee {output}
             done
         fi
@@ -148,8 +178,18 @@ rule run_differential_as_tools:
             for tool in {params.tools}
             do
                 echo "Started $tool at $(date)" | tee {output}
-                docker pull gitlab.lrz.de:5005/ge46ban/dockers/develop/$tool
-                docker run -v {working_directory}:/MOUNT --user $(id -u):$(id -g) --rm {docker_prefix}$tool
+
+                if docker-compose -f scripts/snakemake/docker-compose.yml build $tool ; then
+                    echo "Build $tool locally" | tee {output}
+                    container_prefix="dicast/"
+                else 
+                    echo "\nLocal build failed, pulling image from registry" | tee {output}
+                    docker pull {docker_prefix}$tool:{container_version}
+                    echo "Done" | tee {output}
+                    container_prefix={docker_prefix}
+                fi
+
+                docker run -v {working_directory}:/MOUNT --user $(id -u):$(id -g) --rm $container_prefix"$tool":{container_version}
                 echo "Finished $tool at $(date)" | tee {output}
             done
         fi
@@ -174,11 +214,11 @@ rule finished_run_rule:
 onsuccess:
     shell(
         r"""
-	if ! [[ -f Snakefile && -f snakemake_config.yaml ]];
-	then
-		echo "To create the html report, make sure that the Snakefile and snakemake_config.yaml exist in the working directory."
-		exit 0
-	fi
+        if ! [[ -f Snakefile && -f snakemake_config.yaml ]];
+        then
+            echo "To create the html report, make sure that the Snakefile and snakemake_config.yaml exist in the working directory."
+            exit 0
+        fi
         touch {report_out}
         snakemake --configfile snakemake_config.yaml --unlock
         snakemake --configfile snakemake_config.yaml --report {report_out}
